import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F6F8FB',
  },
  safeAreaDark: {
    backgroundColor: '#12151A',
  },
  screen: {
    alignItems: 'center',
    gap: 18,
    paddingHorizontal: 14,
    paddingBottom: 26,
    paddingTop: 12,
  },
  topBar: {
    alignItems: 'center',
    alignSelf: 'stretch',
    flexDirection: 'row',
    justifyContent: 'space-between',
    maxWidth: 430,
    width: '100%',
  },
  appName: {
    color: '#171B22',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 38,
  },
  caption: {
    color: '#667085',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 2,
  },
  captionDark: {
    color: '#AAB5C2',
  },
  textLight: {
    color: '#F5F8FC',
  },
  resetButton: {
    alignItems: 'center',
    backgroundColor: '#171B22',
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  pressed: {
    opacity: 0.78,
  },
  scoreRow: {
    flexDirection: 'row',
    gap: 8,
    maxWidth: 430,
    width: '100%',
  },
  scorePanel: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 68,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  panelDark: {
    backgroundColor: '#1A1F27',
    borderColor: '#2A3340',
  },
  scoreLabel: {
    color: '#667085',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  scoreValue: {
    color: '#171B22',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 27,
    marginTop: 4,
  },
  boardShell: {
    alignItems: 'center',
    backgroundColor: '#CED8E5',
    borderColor: '#AAB8CA',
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 0,
  },
  boardShellDark: {
    backgroundColor: '#181D25',
    borderColor: '#2A3340',
  },
  board: {
    position: 'relative',
  },
  cell: {
    borderRadius: 7,
    borderWidth: 1,
    position: 'absolute',
  },
  gameOverLayer: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    backgroundColor: '#111827BB',
    justifyContent: 'center',
    padding: 24,
  },
  gameOverPanel: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    gap: 8,
    padding: 18,
    width: '86%',
  },
  gameOverTitle: {
    color: '#171B22',
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
  },
  gameOverScore: {
    color: '#516173',
    fontSize: 16,
    fontWeight: '800',
  },
  playAgainButton: {
    alignItems: 'center',
    backgroundColor: '#171B22',
    borderRadius: 8,
    height: 44,
    justifyContent: 'center',
    marginTop: 4,
    paddingHorizontal: 18,
  },
  playAgainText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  tray: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    minHeight: 112,
  },
  pieceCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 2,
    height: 104,
    justifyContent: 'center',
  },
  pieceCardDark: {
    backgroundColor: '#1A1F27',
    borderColor: '#2A3340',
  },
  emptyPieceCard: {
    opacity: 0.45,
  },
  emptyPieceDot: {
    backgroundColor: '#CBD5E1',
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  miniPiece: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniPieceRow: {
    flexDirection: 'row',
    gap: 3,
  },
  miniCell: {
    borderRadius: 5,
    borderWidth: 1,
    marginBottom: 3,
  },
  statusBar: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  statusText: {
    color: '#4D5C6E',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  galleryScreen: {
    gap: 10,
    padding: 18,
    paddingBottom: 32,
  },
  galleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingTop: 8,
  },
  galleryCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E2E8F0',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    height: 118,
    justifyContent: 'center',
    width: '47.8%',
  },
  galleryLabel: {
    color: '#171B22',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
});
